default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  user: jamlist-rails-project
  password: postgres
  database: jamlist_development

test:
  <<: *default
  host: localhost
  user: jamlist-rails-project
  password: postgres
  database: jamlist_test


production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: jamlist_production